issuer_seed: "<YOUR_ISSUER_SEED>"
hot_seed: "<YOUR_HOT_SEED>"
system_owner_seed: "<YOUR_SYSTEM_OWNER_SEED>"
nft_buyer_seed: "<YOUR_NFT_BUYER_SEED>"
issuer_address: "r3S15u4jgVru2wzHDbhyzjMhGBCXvozQWR"
hot_address: "rUowmT93AQ4ag2C4onY29sVRTNbmqXqQWQ"
system_owner_address: "rNeTREnTe9kXUoGqS2LH4kL8uQVgZzCH5a"
nft_buyer_address: "rsgpdWshJQYRVkDLEHtHJWFzxLoEs6cFe4"
## Central NFT minter (authority that mints SOLRAI NFTs)
nft_minter_seed: "<YOUR_NFT_MINTER_SEED>"
nft_minter_address: "<YOUR_NFT_MINTER_ADDRESS>"
currency_code: "STN"
jurisdiction: "US-NJ"
program: "NJ-SREC"
vintage: "2025"
meter_hash: "<hash-of-meter-data>"
oracle_reference: "<URL-or-hash-of-signed-data>"
price_usd: "90"
price_xrp_drops: "<XRP_drops_for_90USD>"
image_path: "IMG_A6FBCF8F-9700-4089-ADB0-5C914EF43766.jpeg"

# Compliance-focused fields for REC representation
facility_name: "Mock Solar Plant #1"
facility_location: "123 Sunshine Ave, Trenton, NJ"
grid_region: "PJM"
technology: "Solar PV"
vintage_start: "2025-01-01"
vintage_end: "2025-12-31"
rec_serial_prefix: "SOLRAI-NJ-2025-"
schema_version: "1.0"

# Optional Xaman/Xumm config (provide via environment variables in production)
# xumm_api_key: "<XUMM_API_KEY>"
# xumm_api_secret: "<XUMM_API_SECRET>"
